import type { Vehicle } from "../src/lib/vehicles";

const MEDIA = "https://pub-9fd15a1bea4c403d9e48728f2e707eed.r2.dev/catalog/generations";

export const demoVehicles: Vehicle[] = [
  {
    slug: "honda-nsx-na1-marta",
    owner: { name: "Marta" },
    make: "Honda",
    model: "NSX",
    variant: "NA1 3.0",
    year: 1993,
    engine: "C30A, 3.0 V6 VTEC",
    powerHp: 274,
    paintCode: "R-81 Formula Red",
    mileageKm: 118400,
    status: "weekend",
    photo: `${MEDIA}/9366-7c0acb44d3/1280.webp`,
    generationId: 9366,
    catalogPath: "/katalog/honda/nsx",
    flames: 0,
    mods: [
      { category: "Rozrząd", part: "Pasek + pompa wody OEM (wymiana co 90 tys. km)" },
      { category: "Koła", part: "OEM 15/16\" z odnowionym lakierem" },
      { category: "Zawieszenie", part: "Amortyzatory Bilstein B6" },
    ],
    timeline: [
      {
        date: "2026-08-30",
        title: "Rozrząd i pompa wody",
        kind: "service",
        mileageKm: 118000,
        note: "Pasek, rolki, pompa wody i termostat. Przy okazji nowe paski osprzętu. Silnik bez zarzutu.",
        flames: 0,
      },
      {
        date: "2026-05-12",
        title: "Odnowione felgi i geometria",
        kind: "mod",
        mileageKm: 116900,
        note: "Proszek w oryginalnym kolorze, nowe opony Bridgestone Potenza, geometria wg specyfikacji fabrycznej.",
        flames: 0,
      },
      {
        date: "2025-10-04",
        title: "Dzień toru - Poznań",
        kind: "track",
        mileageKm: 115200,
        note: "Trzy sesje po 20 minut, zero problemów z temperaturą. Najlepsze okrążenie 1:58,9.",
        flames: 0,
      },
    ],
  },
  {
    slug: "honda-integra-type-r-dc2-piotr",
    owner: { name: "Piotr" },
    make: "Honda",
    model: "Integra",
    variant: "Type R DC2",
    year: 1996,
    engine: "B18C, 1.8 VTEC",
    powerHp: 200,
    paintCode: "NH-0 Championship White",
    mileageKm: 214300,
    status: "build",
    photo: `${MEDIA}/6003-ca889f67a4/1280.webp`,
    generationId: 6003,
    catalogPath: "/katalog/honda/integra",
    flames: 0,
    mods: [
      { category: "Zawieszenie", part: "Tein Flex Z + górne mocowania Hardrace" },
      { category: "Koła", part: "Enkei RPF1, 15×7 ET38" },
      { category: "Hamulce", part: "Klocki Ferodo DS2500, przewody w oplocie" },
    ],
    timeline: [
      {
        date: "2026-09-18",
        title: "Nowy zawór IACV i czyszczenie przepustnicy",
        kind: "service",
        mileageKm: 214200,
        note: "Obroty dalej falują na zimnym - temat w dziale Usterki.",
        flames: 0,
      },
      {
        date: "2026-06-02",
        title: "Tein Flex Z",
        kind: "mod",
        mileageKm: 212800,
        note: "Obniżenie 30 mm przód / 25 mm tył, tłumienie 8/16 klików. Geometria z lekkim ujemnym pochyleniem.",
        flames: 0,
      },
    ],
  },
  {
    slug: "honda-civic-type-r-fn2-tomek",
    owner: { name: "Tomek", verifiedMechanic: true },
    make: "Honda",
    model: "Civic",
    variant: "Type R FN2",
    year: 2007,
    engine: "K20Z4, 2.0 i-VTEC",
    powerHp: 201,
    paintCode: "R-81 Milano Red",
    mileageKm: 161000,
    status: "track",
    photo: `${MEDIA}/771-aed7ee2946/1280.webp`,
    generationId: 771,
    catalogPath: "/katalog/honda/civic",
    flames: 0,
    mods: [
      { category: "Zawieszenie", part: "Bilstein B16 PSS10" },
      { category: "Hamulce", part: "Tarcze 320 mm + klocki Ferodo DS2500" },
      { category: "Napęd", part: "Szpera Quaife ATB" },
    ],
    timeline: [
      {
        date: "2026-09-02",
        title: "Montaż Bilstein B16",
        kind: "mod",
        mileageKm: 160800,
        note: "Pełna instrukcja ze zdjęciami w wątku na forum. Ustawienia: 4/10 przód, 6/10 tył.",
        flames: 0,
      },
    ],
  },
  {
    slug: "infiniti-g37s-kasia",
    owner: { name: "Kasia" },
    make: "Infiniti",
    model: "G37",
    variant: "S Sedan V36",
    year: 2011,
    engine: "VQ37VHR, 3.7 V6",
    powerHp: 333,
    paintCode: "KAD Graphite Shadow",
    mileageKm: 142000,
    status: "daily",
    photo: `${MEDIA}/909-68a5a4f9da/1280.webp`,
    generationId: 909,
    catalogPath: "/katalog/infiniti/g-series",
    flames: 0,
    mods: [
      { category: "Koła", part: "Work Emotion CR Kiwami, 19×9.5 ET22" },
      { category: "Wydech", part: "Tłumiki końcowe Invidia Q300" },
      { category: "Zawieszenie", part: "Sprężyny Eibach Pro-Kit" },
    ],
    timeline: [
      {
        date: "2026-07-21",
        title: "Koła 19×9.5 i rolowanie rantów",
        kind: "mod",
        mileageKm: 141600,
        note: "Z oponami 265/35 R19 tył ocierał na nierównościach - po rolowaniu i −1,5° pochylenia jest czysto.",
        flames: 0,
      },
    ],
  },
];
